import pineapple from "../../assets/FruitsImages/f2.png";
import grapes from "../../assets/FruitsImages/f4.png";
import strawberry from "../../assets/FruitsImages/f5.png";
import cherry from "../../assets/FruitsImages/f8.png";
import banana from "../../assets/FruitsImages/f9.png";
import watermelon from "../../assets/FruitsImages/f10.png";
import redbul from "../../assets/CoolDrinksImages/d1.png";
import pepsi from "../../assets/CoolDrinksImages/d2.png";
import monster from "../../assets/CoolDrinksImages/d3.png";
import sprite from "../../assets/CoolDrinksImages/d5.png";
import fanta from "../../assets/CoolDrinksImages/d6.png";
import cola from "../../assets/CoolDrinksImages/d8.png";

const EData = [
  {
    id: 1,
    category: "Men",
    name: "Globus",
    image:
      "https://m.media-amazon.com/images/I/61qXib9mR5L._AC_SR350,526_FMwebp_QL65_.jpg",
    price: "$10",
  },
  {
    id: 2,
    category: "Men",
    name: "ZOSOE",
    image: "https://m.media-amazon.com/images/I/81Lvtp4EoYL._UX342_.jpg",
    price: "$19",
  },
  {
    id: 3,
    category: "Men",
    name: "U-Turn",
    image: "https://m.media-amazon.com/images/I/41JVgTrS9RL._AC_UL320_.jpg",
    price: "$17",
  },
  {
    id: 4,
    category: "Men",
    name: "IndoPrimo",
    image: "https://m.media-amazon.com/images/I/61RqedeafJL._AC_UL320_.jpg",
    price: "$20",
  },
  {
    id: 5,
    category: "Men",
    name: "Dennis Lingo",
    image: "https://m.media-amazon.com/images/I/61YQd1wdQBL._AC_UL320_.jpg",
    price: "$8",
  },
  {
    id: 6,
    category: "Men",
    name: "Majestic Man",
    image: "https://m.media-amazon.com/images/I/51SHcquULjL._AC_UL320_.jpg",
    price: "$8",
  },
  {
    id: 7,
    category: "Men",
    name: "Peppyzone",
    image: "https://m.media-amazon.com/images/I/61SshsOircL._AC_UL320_.jpg",
    price: "$40",
  },
  {
    id: 8,
    category: "Men",
    name: "Van Heusen",
    image: "https://m.media-amazon.com/images/I/51FRSZ51K7L._AC_UL320_.jpg",
    price: "$6",
  },
  {
    id: 9,
    category: "Men",
    name: "Maniac",
    image: "https://m.media-amazon.com/images/I/615EkX-wPxL._AC_UL320_.jpg",
    price: "$10",
  },
  {
    id: 10,
    category: "Men",
    name: "Slim Pant",
    image: "https://m.media-amazon.com/images/I/91ddSsAzq-L._AC_UL320_.jpg",
    price: "$20",
  },
  {
    id: 11,
    category: "Men",
    name: "Kraasa",
    image: "https://m.media-amazon.com/images/I/61VSXhTepEL._AC_UL320_.jpg",
    price: "$100",
  },
  {
    id: 12,
    category: "Men",
    name: "WoodLand",
    image: "https://m.media-amazon.com/images/I/814X04ca4rL._AC_UL320_.jpg",
    price: "$90",
  },
  {
    id: 13,
    category: "Men",
    name: "WMX",
    image: "https://m.media-amazon.com/images/I/71wTmZLgKoL._AC_UL320_.jpg",
    price: "$6",
  },
  {
    id: 14,
    category: "Men",
    name: "Louis Stitch",
    image: "https://m.media-amazon.com/images/I/511u+xX-ZoL._AC_UL320_.jpg",
    price: "$50",
  },
  {
    id: 15,
    category: "Men",
    name: "Formal Shirt",
    image: "https://m.media-amazon.com/images/I/71umJqZLmZL._AC_UL320_.jpg",
    price: "$20",
  },

  {
    id: 16,
    category: "Women",
    name: "RaRe",
    image: "https://m.media-amazon.com/images/I/71nWkTTddlL._AC_UL320_.jpg",
    price: "$20",
  },
  {
    id: 17,
    category: "Women",
    name: "Lymio",
    image: "https://m.media-amazon.com/images/I/81WCsJTc0FL._AC_UL320_.jpg",
    price: "$29",
  },
  {
    id: 18,
    category: "Women",
    name: "GRECIILOOKS",
    image: "https://m.media-amazon.com/images/I/61KdLwVl+iL._AC_UL320_.jpg",
    price: "$17",
  },
  {
    id: 19,
    category: "Women",
    name: "OOMPH!",
    image: "https://m.media-amazon.com/images/I/91qZkCKhdNL._AC_UL320_.jpg",
    price: "$120",
  },
  {
    id: 20,
    category: "Women",
    name: "Dennis Lingo",
    image: "https://m.media-amazon.com/images/I/71+R-Y5ucKL._AC_UL320_.jpg",
    price: "$18",
  },
  {
    id: 21,
    category: "Women",
    name: "SWORNOF",
    image: "https://m.media-amazon.com/images/I/814cEyVGvVL._AC_UL320_.jpg",
    price: "$28",
  },
  {
    id: 22,
    category: "Women",
    name: "Peppyzone",
    image: "https://m.media-amazon.com/images/I/81PQzjgHjnL._AC_UL320_.jpg",
    price: "$30",
  },
  {
    id: 23,
    category: "Women",
    name: "HITHROW",
    image: "https://m.media-amazon.com/images/I/61VLf337lRL._AC_UL320_.jpg",
    price: "$60",
  },
  {
    id: 24,
    category: "Women",
    name: "Maniac",
    image: "https://m.media-amazon.com/images/I/81d3St+cQ4L._AC_UL320_.jpg",
    price: "$100",
  },
  {
    id: 25,
    category: "Women",
    name: "Tarshika",
    image: "https://m.media-amazon.com/images/I/81et1Cqb+gL._AC_UL320_.jpg",
    price: "$200",
  },
  {
    id: 26,
    category: "Women",
    name: "EKYLIP",
    image: "https://m.media-amazon.com/images/I/51GcX-zYPLL._AC_UL320_.jpg",
    price: "$300",
  },
  {
    id: 27,
    category: "Women",
    name: "Speed X Fashion",
    image: "https://m.media-amazon.com/images/I/81BZA7WpfnL._AC_UL320_.jpg",
    price: "$190",
  },
  {
    id: 28,
    category: "Women",
    name: "Women Handbag",
    image: "https://m.media-amazon.com/images/I/719q0YeZvoL._AC_UL320_.jpg",
    price: "$600",
  },
  {
    id: 29,
    category: "Women",
    name: "Sasitrends",
    image: "https://m.media-amazon.com/images/I/51oOs6x-26L._AC_UL320_.jpg",
    price: "$50",
  },
  {
    id: 30,
    category: "Women",
    name: "Sukkhi",
    image: "https://m.media-amazon.com/images/I/912iX-Sve0L._AC_UL320_.jpg",
    price: "$200",
  },

  {
    id: 31,
    category: "Kids",
    name: "Kids Toy",
    image: "https://m.media-amazon.com/images/I/61diAATmq3L._AC_UL320_.jpg",
    price: "$12",
  },
  {
    id: 32,
    category: "Kids",
    name: "Teddy",
    image: "https://m.media-amazon.com/images/I/61d9TJqbVTL._AC_UL320_.jpg",
    price: "$19",
  },
  {
    id: 33,
    category: "Kids",
    name: "Ride car",
    image: "https://m.media-amazon.com/images/I/71K3VcPDaGL._AC_UL320_.jpg",
    price: "$17",
  },
  {
    id: 34,
    category: "Kids",
    name: "Car",
    image: "https://m.media-amazon.com/images/I/51+PhlV7NgL._AC_UL320_.jpg",
    price: "$220",
  },
  {
    id: 35,
    category: "Kids",
    name: "KATS SHOES",
    image: "https://m.media-amazon.com/images/I/81NNEgVX-rL._AC_UL320_.jpg",
    price: "$88",
  },
  {
    id: 36,
    category: "Kids",
    name: "Child Sneaker",
    image: "https://m.media-amazon.com/images/I/81GOMSmsSeL._AC_UL320_.jpg",
    price: "$18",
  },
  {
    id: 37,
    category: "Kids",
    name: "Max",
    image: "https://m.media-amazon.com/images/I/91xIK5XlIrL._AC_UL320_.jpg",
    price: "$30",
  },
  {
    id: 38,
    category: "Women",
    name: "T2F",
    image: "https://m.media-amazon.com/images/I/61xBN-cUMDL._AC_UL320_.jpg",
    price: "$40",
  },
  {
    id: 39,
    category: "Women",
    name: "Ellipse FASHION",
    image: "https://m.media-amazon.com/images/I/71z1MRo3VtL._AC_UL320_.jpg",
    price: "$80",
  },
  {
    id: 40,
    category: "FruitsAndBeverage",
    name: "Redbul",
    image: redbul,
    price: "$9",
  },
  {
    id: 41,
    category: "FruitsAndBeverage",
    name: "pepsi",
    image: pepsi,
    price: "$3",
  },
  {
    id: 42,
    category: "FruitsAndBeverage",
    name: "Monster",
    image: monster,
    price: "$19",
  },
  {
    id: 43,
    category: "FruitsAndBeverage",
    name: "Sprite",
    image: sprite,
    price: "$6",
  },
  {
    id: 44,
    category: "FruitsAndBeverage",
    name: "Fanta",
    image: fanta,
    price: "$5",
  },
  {
    id: 45,
    category: "FruitsAndBeverage",
    name: "cocacola",
    image: cola,
    price: "$10",
  },
  {
    id: 46,
    category: "FruitsAndBeverage",
    name: "Pineapple",
    image: pineapple,
    price: "$20",
  },
  {
    id: 47,
    category: "FruitsAndBeverage",
    name: "Grapes",
    image: grapes,
    price: "$10",
  },
  {
    id: 48,
    category: "FruitsAndBeverage",
    name: "Strawberry",
    image: strawberry,
    price: "$18",
  },
  {
    id: 49,
    category: "FruitsAndBeverage",
    name: "Banana",
    image: banana,
    price: "$8",
  },
  {
    id: 50,
    category: "FruitsAndBeverage",
    name: "Cherry",
    image: cherry,
    price: "$8",
  },
  {
    id: 51,
    category: "FruitsAndBeverage",
    name: "watermelon",
    image: watermelon,
    price: "$16",
  },

  {
    id: 52,
    category: "Phones",
    name: "Samsung  5G",
    image: "https://m.media-amazon.com/images/I/91HRACirFrL._AC_UY218_.jpg",
    price: "$700",
  },
  {
    id: 53,
    category: "Phones",
    name: "Apple iPhone13",
    image: "https://m.media-amazon.com/images/I/71gm8v4uPBL._AC_UY218_.jpg",
    price: "$1900",
  },
  {
    id: 54,
    category: "Phones",
    name: "Oppo A15",
    image: "https://m.media-amazon.com/images/I/71TdXNLT1FL._AC_UY218_.jpg",
    price: "$870",
  },
  {
    id: 55,
    category: "Phones",
    name: "realme  N55",
    image: "https://m.media-amazon.com/images/I/71Ftzmh3XWL._AC_UY218_.jpg",
    price: "$620",
  },
  {
    id: 56,
    category: "Phones",
    name: "Apple iPhone 14 ",
    image: "https://m.media-amazon.com/images/I/71ZDY57yTQL._AC_UY218_.jpg",
    price: "$1900",
  },
  {
    id: 57,
    category: "Phones",
    name: "Redmi Note 12",
    image: "https://m.media-amazon.com/images/I/81ZZPvIWnYL._AC_UY218_.jpg",
    price: "$980",
  },
  {
    id: 58,
    category: "Phones",
    name: "OnePlus Lite 5G",
    image: "https://m.media-amazon.com/images/I/61QRgOgBx0L._AC_UY218_.jpg",
    price: "$700",
  },
  {
    id: 59,
    category: "Phones",
    name: "Poco M3",
    image: "https://m.media-amazon.com/images/I/81CccCunTsS._AC_UY218_.jpg",
    price: "$300",
  },
  {
    id: 60,
    category: "Phones",
    name: "Vivo y22",
    image: "https://m.media-amazon.com/images/I/618DANgK-QL._AC_UY218_.jpg",
    price: "$350",
  },

  {
    id: 61,
    category: "Electronics",
    name: "WiFi CCTV",
    image: "https://m.media-amazon.com/images/I/31Nk80-hUUL._AC_UL320_.jpg",
    price: "$90",
  },
  {
    id: 62,
    category: "Electronics",
    name: "Electric Drill Tool Set",
    image: "https://m.media-amazon.com/images/I/81fP7IRuKKL._AC_UL320_.jpg",
    price: "$30",
  },
  {
    id: 63,
    category: "Electronics",
    name: "Vacuum Cleaner",
    image: "https://m.media-amazon.com/images/I/715l1odFnbL._AC_UL320_.jpg",
    price: "$19",
  },
  {
    id: 64,
    category: "Electronics",
    name: "UPS",
    image: "https://m.media-amazon.com/images/I/51+xYuXifNL._AC_UL320_.jpg",
    price: "$60",
  },
  {
    id: 65,
    category: "Electronics",
    name: "Mixer grinder",
    image: "https://m.media-amazon.com/images/I/71G3OBnz8pL._AC_UL320_.jpg",
    price: "$50",
  },
  {
    id: 66,
    category: "Electronics",
    name: "Earbuds",
    image: "https://m.media-amazon.com/images/I/51HBom8xz7L._AC_UY218_.jpg",
    price: "$90",
  },
  {
    id: 67,
    category: "Electronics",
    name: "OnePlus Buds 2",
    image: "https://m.media-amazon.com/images/I/61-ZYvldY+L._AC_UY218_.jpg",
    price: "$120",
  },
  {
    id: 68,
    category: "Electronics",
    name: "webcam",
    image: "https://m.media-amazon.com/images/I/61HfJn05shL._AC_UY218_.jpg",
    price: "$70",
  },
  {
    id: 69,
    category: "Electronics",
    name: "Logitech Webcam",
    image: "https://m.media-amazon.com/images/I/61yo4swj-PL._AC_UY218_.jpg",
    price: "$90",
  },
  {
    id: 70,
    category: "Electronics",
    name: "ZEBRONICS Camera",
    image: "https://m.media-amazon.com/images/I/71fKEMwMWYL._AC_UY218_.jpg",
    price: "$80",
  },
  {
    id: 71,
    category: "Electronics",
    name: "Whirlpool Refrigerator",
    image: "https://m.media-amazon.com/images/I/51AWK+09OIL._AC_UY218_.jpg",
    price: "$580",
  },
  {
    id: 72,
    category: "Electronics",
    name: "Voltas Refrigerator",
    image: "https://m.media-amazon.com/images/I/51pJVpAFwPL._AC_UY218_.jpg",
    price: "$600",
  },
];

export default EData;
